resolver: lts-9.21

packages:
- '../macbeth-fics'
- '../macbeth-wx'
- './'

explicit-setup-deps:
    "*": true

extra-deps: 
- ALUT-2.4.0.2
- cabal-macosx-0.2.4.2
- FindBin-0.0.5 
- hspec-2.5.1
- hspec-core-2.5.1
- hspec-discover-2.5.1
- hspec-expectations-0.8.2
- HUnit-1.6.0.0
- OpenAL-1.7.0.4
- QuickCheck-2.11.3
- quickcheck-io-0.2.0
- wx-0.92.2.0
- wxcore-0.92.2.0
- wxc-0.92.2.0
- wxdirect-0.92.2.0
